### ISSUE TITLE
INetAddress.isReachable returns false for reachable addresses

### ISSUE THREAD

**Issue by parkeristyping** [danielsz/certificaat#2]
I'm trying to use this library to set up a cert with Let's Encrypt and running into the following error:

``` bash
$ certificaat authorize -m google.com -a me@example.com -c http-01 -u acme://letsencrypt.org/staging
Failed to validate "-m google.com": Must be a valid domain
```

(I'm obviously not trying to get a cert for google.com, but I've used that as the example since it's clearly a valid domain.)

The issue seems to stem from the use of `.isReachable` in the specs:

``` clojure
(.isReachable (InetAddress/getByName "google.com") 5000)
;;=> false
```

Not sure why that would be or if it has to do with my environment (I see the same behavior on my Mac and a fresh amazon linux box, both with Java 1.8). Seems I'm not the only one to have issues with `INetAddress.isReachable`, though. See: https://stackoverflow.com/questions/9922543/why-does-inetaddress-isreachable-return-false-when-i-can-ping-the-ip-address

Anyone else run into this?

If it is actually an issue and not just me, I see a couple easy options to address it:

- Replace that call to `INetAddress.isReachable` with something else to validate the URL
- Add a command line option to skip that check (I expect leading to issues down the line with the CA if it's actually unreachable, but in my opinion that's better than not even being able to try because of the Spec)

Edit: FYI I do see it work for some sites e.g. `-m wikipedia.org`

**Comment by danielsz** [comment]
Hi, 

Thank you for reporting this. 

On my linux machine with java 1.8, I cannot reproduce this.

```clojure
(.isReachable (InetAddress/getByName "google.com") 5000)
```
That returns `true`, as it does for a string of domains I tested, trying to see if I can get it to return `false`. 

According to the references you included, the call is problematic, so I'm taking note of this. 
Please let me know if you have trouble validating your final domain. Thank you!

**Comment by parkeristyping** [comment]
Thanks for your response.

FYI I was able to get certs for my domain setup fine using Certbot.
